### PR TITLE
added blade-mono-icons set

### PR DESCRIPTION
**Pull request by swapnilsarwe**

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks! Nice to see a set from a known Belgium company swing by 🙂

**Comment by swapnilsarwe** [comment]
There are so many of them, I am unable to stop myself. 
All those icon sets are scattered invisible to us. Now we have place to collaborate them at one single place.

**Comment by driesvints** [comment]
@swapnilsarwe I'm thinking about maybe creating a package template repo under this organization so it's easier for people to create new icon packages. But I want to get https://github.com/blade-ui-kit/blade-icons/pull/144 merged first.

**Comment by swapnilsarwe** [comment]
@driesvints - yes that is a good idea. 
I am using a custom app to compile svg icons, which pull from parent repositories & process them as required. 
But as per the other stuff (customizing Service Provider, writing test & updating README) is concerned, that is completely manual. 

I will go through #144 , and put my learnings from my custom app to it as much as possible to enrich it. Give me few days.

**Pull request merged**
