### PR TITLE
added coreui icons & simple-icons

### PR DESCRIPTION
**Pull request by adrian-ub**

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks. I've removed the simple icons listen however because we already have that package.

**Comment by driesvints** [comment]
@adrian-ub your Simple Icons package was added here: https://github.com/blade-ui-kit/blade-icons/pull/139 by @scrlkx because the other one wasn't updated yet. Thanks!

**Comment by adrian-ub** [comment]
Thanks for adding the package!

**Comment by swapnilsarwe** [comment]
well nothing against adding ublabs/blade-simple-icons package, but the codeat3/blade-simple-icons package was removed so that we don't have duplicate packages. #134 
now there are 3 duplicates of simple-icons packages
1. @sadegh19b - https://github.com/sadegh19b/blade-brand-icons ([85 downloads](https://packagist.org/packages/sadegh19b/blade-brand-icons)) - which is not maintained
2. @swapnilsarwe - https://github.com/codeat3/blade-simple-icons ([366 downloads](https://packagist.org/packages/codeat3/blade-simple-icons))
3. @adrian-ub - https://github.com/ublabs/blade-simple-icons ([2 downloads](https://packagist.org/packages/ublabs/blade-simple-icons))

**Comment by driesvints** [comment]
I'm gonna keep the one from @adrian-ub since it's the only one in the list now

**Comment by swapnilsarwe** [comment]
cool

**Pull request merged**
