### PR TITLE
Added Make Lemonade's Iconic icons

### PR DESCRIPTION
**Pull request by ItsMalikJones**

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks @ItsMalikJones! :)

If you're up for it, you can also send a PR to the blade-ui-kit.com repo to add them to the icon search.

**Comment by Cigoler** [comment]
If I wanted to add the 'pro' icons to this set how would I go about it? Is that possible by editing the config?

**Comment by driesvints** [comment]
@Cigoler best to ask on the related repo

**Comment by Cigoler** [comment]
> @Cigoler best to ask on the related repo

Sorry, I wasn't able to which is why I headed here - I seem to get a 404 error adding any issue on his repo for some reason.

**Comment by driesvints** [comment]
@Cigoler in that case it's best to contact GitHub support

**Pull request merged**
