### PR TITLE
Add Remix Icon package

### PR DESCRIPTION
**Pull request by skydiver**

### CODE REVIEW

**Comment by driesvints** [comment]
Heya I added this manually because of a merge conflict. Thanks!

**Comment by Wulfheart** [comment]
🤦‍♂️
Noooo! Just did the same. Merged 5 minutes earlier and I wouldn't have made that [package.  😢](https://github.com/Wulfheart/blade-remixicon)
May I still submit it? 👼

**Comment by driesvints** [comment]
@Wulfheart ah too bad. Heh, sorry but I don't think it makes sense to list two packages.

**Comment by Wulfheart** [comment]
Makes sense.

**Pull request closed without merging**
