### PR TITLE
Add cache command

### PR DESCRIPTION
**Pull request by mvdnbrk**
See https://github.com/blade-ui-kit/blade-icons/issues/71#issuecomment-671282599

WIP

### CODE REVIEW

**Comment by inxilpro** [comment]
@mvdnbrk anything you need help with to finalize this?

**Comment by mvdnbrk** [comment]
Sorry didn't have much time to dive further into this.

I think we need some more modifications, particularly how icon sets are registered in the package.

Can you take a look @driesvints and share your thoughts?

**Comment by driesvints** [comment]
I'n sorry I didn't get to this. Last weeks have been extra busy for me. I'm hoping to get to these prs/issues soon.

**Comment by mvdnbrk** [comment]
Take a breath @driesvints no worries. If there is anything I can do to help you keep things going please let me know. Would be glad to help :smile:

**Comment by driesvints** [comment]
Hi @mvdnbrk. I'm sorry it took me this long to get to this. I've continued your work in a new PR here: https://github.com/blade-ui-kit/blade-icons/pull/121. I'm looking for people who want to help me test here: https://github.com/blade-ui-kit/blade-icons/pull/121#issuecomment-798906016

This will be included in the upcoming 1.0 release.

**Pull request closed without merging**
