### PR TITLE
Update readme to reflect auto-registering service provider

### PR DESCRIPTION
**Pull request by calebporzio**
Me: Do I really have to register the service provider myself like the pioneers used to do?

Me: I better just check first and see if it auto-registers.

Me: Ok, phew, it does.

Me: I should PR this to save thousands of developers from the same toils.

Also, I actually came here to PR a change to the config to reflect the new `resources` directory stuff: `resources/assets` -> `resources/`. But it looks like someone already did, but change isn't tagged...

...you should tag it...

### CODE REVIEW

**Comment by adamwathan** [comment]
Oh hey @calebporzio, bad news, you're a collaborator on this repo now and will have to tag your own releases and merge your own PRs. I don't write PHP anymore I just write books and play Rocket League.

**Comment by calebporzio** [comment]
Pshh... you changed...

**Comment by dillingham** [comment]
@calebporzio can you tag a release :)

Kind would love to not publish a config for assets dir https://github.com/adamwathan/blade-svg/pull/30 that was merged

**Comment by calebporzio** [comment]
Lol, yes I will

**Comment by dillingham** [comment]
Thanks @calebporzio! Haha

**Pull request merged**
