### PR TITLE
Alternative title, for the sake of accessibility

### PR DESCRIPTION
**Pull request by meduzen**
_Disclaimer: that’s my first pull request day, and as a front-end guy, my PHP experience is rather low._

Fixing #12 in two commits, _4791549_ for SVG rendered from spritesheet, _bc85892_ for inline rendering (this last one was a bit tricky). I have no experience at all in unit tests, but I manually tried a lot of cases and all seemed OK.

Many thanks for your job for the Laravel community.

### CODE REVIEW

**Comment by meduzen** [comment]
Hi @adamwathan ; seeing you around these days. Is there anything I can do to help for this feature-request? Or do you keep it for another time?

**Comment by adamwathan** [comment]
Hey @meduzen, have been putting this off because it feels complicated and I'm hoping there's a simpler way to solve it :/ I also noticed at least one bug, where the `spritesheetUrl()` function is no longer used when rendering an SVG from an external spritesheet.

If you can revert that change regarding the `spritesheetUrl` stuff, remove the code that handles duplicate classes (I'm not worried about that personally; at least not as part of this PR), and try to add some tests I can look at it in more detail.

Check out the existing test file; it's really simple and you can probably get your head around it just by copying and pasting and existing test and modifying it to check for the new title tag.

You should be able to just run `./vendor/bin/phpunit` from inside the `blade-svg` project folder to get the tests running 👍

**Comment by meduzen** [comment]
Thanks for your feedback.

I still don’t know when I’ll have time to dig in it, but I’ll make sure everything is compliant with the latest version of the package.

**Comment by driesvints** [comment]
Heya, I'm going to close this for now as this will conflict quite a bit with #50. Let's discuss further in the related issue to see how we can best tackle this.

**Pull request closed without merging**
